//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
// 
#pragma warning disable 1591

namespace ClientApplication.BlockBusterCinema {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CinemaServiceSoap", Namespace="http://sd.isel.pt/")]
    public partial class CinemaService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMoviesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMoviesByTitleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMoviesByPeriodOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddReservationOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveReservationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CinemaService() {
            this.Url = global::ClientApplication.Properties.Settings.Default.ClientApplication_BlockBusterCinema_CinemaService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMoviesCompletedEventHandler GetMoviesCompleted;
        
        /// <remarks/>
        public event GetMoviesByTitleCompletedEventHandler GetMoviesByTitleCompleted;
        
        /// <remarks/>
        public event GetMoviesByPeriodCompletedEventHandler GetMoviesByPeriodCompleted;
        
        /// <remarks/>
        public event AddReservationCompletedEventHandler AddReservationCompleted;
        
        /// <remarks/>
        public event RemoveReservationCompletedEventHandler RemoveReservationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sd.isel.pt/GetMovies", RequestNamespace="http://sd.isel.pt/", ResponseNamespace="http://sd.isel.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Movie[] GetMovies() {
            object[] results = this.Invoke("GetMovies", new object[0]);
            return ((Movie[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMoviesAsync() {
            this.GetMoviesAsync(null);
        }
        
        /// <remarks/>
        public void GetMoviesAsync(object userState) {
            if ((this.GetMoviesOperationCompleted == null)) {
                this.GetMoviesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMoviesOperationCompleted);
            }
            this.InvokeAsync("GetMovies", new object[0], this.GetMoviesOperationCompleted, userState);
        }
        
        private void OnGetMoviesOperationCompleted(object arg) {
            if ((this.GetMoviesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMoviesCompleted(this, new GetMoviesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sd.isel.pt/GetMoviesByTitle", RequestNamespace="http://sd.isel.pt/", ResponseNamespace="http://sd.isel.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Movie[] GetMoviesByTitle(string[] keyWords) {
            object[] results = this.Invoke("GetMoviesByTitle", new object[] {
                        keyWords});
            return ((Movie[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMoviesByTitleAsync(string[] keyWords) {
            this.GetMoviesByTitleAsync(keyWords, null);
        }
        
        /// <remarks/>
        public void GetMoviesByTitleAsync(string[] keyWords, object userState) {
            if ((this.GetMoviesByTitleOperationCompleted == null)) {
                this.GetMoviesByTitleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMoviesByTitleOperationCompleted);
            }
            this.InvokeAsync("GetMoviesByTitle", new object[] {
                        keyWords}, this.GetMoviesByTitleOperationCompleted, userState);
        }
        
        private void OnGetMoviesByTitleOperationCompleted(object arg) {
            if ((this.GetMoviesByTitleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMoviesByTitleCompleted(this, new GetMoviesByTitleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sd.isel.pt/GetMoviesByPeriod", RequestNamespace="http://sd.isel.pt/", ResponseNamespace="http://sd.isel.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Movie[] GetMoviesByPeriod(System.DateTime start, System.DateTime end) {
            object[] results = this.Invoke("GetMoviesByPeriod", new object[] {
                        start,
                        end});
            return ((Movie[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMoviesByPeriodAsync(System.DateTime start, System.DateTime end) {
            this.GetMoviesByPeriodAsync(start, end, null);
        }
        
        /// <remarks/>
        public void GetMoviesByPeriodAsync(System.DateTime start, System.DateTime end, object userState) {
            if ((this.GetMoviesByPeriodOperationCompleted == null)) {
                this.GetMoviesByPeriodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMoviesByPeriodOperationCompleted);
            }
            this.InvokeAsync("GetMoviesByPeriod", new object[] {
                        start,
                        end}, this.GetMoviesByPeriodOperationCompleted, userState);
        }
        
        private void OnGetMoviesByPeriodOperationCompleted(object arg) {
            if ((this.GetMoviesByPeriodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMoviesByPeriodCompleted(this, new GetMoviesByPeriodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sd.isel.pt/AddReservation", RequestNamespace="http://sd.isel.pt/", ResponseNamespace="http://sd.isel.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid AddReservation(string name, string sessionId, int seats) {
            object[] results = this.Invoke("AddReservation", new object[] {
                        name,
                        sessionId,
                        seats});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public void AddReservationAsync(string name, string sessionId, int seats) {
            this.AddReservationAsync(name, sessionId, seats, null);
        }
        
        /// <remarks/>
        public void AddReservationAsync(string name, string sessionId, int seats, object userState) {
            if ((this.AddReservationOperationCompleted == null)) {
                this.AddReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddReservationOperationCompleted);
            }
            this.InvokeAsync("AddReservation", new object[] {
                        name,
                        sessionId,
                        seats}, this.AddReservationOperationCompleted, userState);
        }
        
        private void OnAddReservationOperationCompleted(object arg) {
            if ((this.AddReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddReservationCompleted(this, new AddReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sd.isel.pt/RemoveReservation", RequestNamespace="http://sd.isel.pt/", ResponseNamespace="http://sd.isel.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RemoveReservation(System.Guid code) {
            object[] results = this.Invoke("RemoveReservation", new object[] {
                        code});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveReservationAsync(System.Guid code) {
            this.RemoveReservationAsync(code, null);
        }
        
        /// <remarks/>
        public void RemoveReservationAsync(System.Guid code, object userState) {
            if ((this.RemoveReservationOperationCompleted == null)) {
                this.RemoveReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveReservationOperationCompleted);
            }
            this.InvokeAsync("RemoveReservation", new object[] {
                        code}, this.RemoveReservationOperationCompleted, userState);
        }
        
        private void OnRemoveReservationOperationCompleted(object arg) {
            if ((this.RemoveReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveReservationCompleted(this, new RemoveReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sd.isel.pt/")]
    public partial class Movie {
        
        private int idField;
        
        private string titleField;
        
        private string descField;
        
        private MovieSession[] sessionsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public MovieSession[] Sessions {
            get {
                return this.sessionsField;
            }
            set {
                this.sessionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sd.isel.pt/")]
    public partial class MovieSession {
        
        private string idField;
        
        private System.DateTime startTimeField;
        
        private int movieIdField;
        
        private int roomIdField;
        
        private Room roomField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public int MovieId {
            get {
                return this.movieIdField;
            }
            set {
                this.movieIdField = value;
            }
        }
        
        /// <remarks/>
        public int RoomId {
            get {
                return this.roomIdField;
            }
            set {
                this.roomIdField = value;
            }
        }
        
        /// <remarks/>
        public Room Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sd.isel.pt/")]
    public partial class Room {
        
        private int numField;
        
        private int capacityField;
        
        /// <remarks/>
        public int Num {
            get {
                return this.numField;
            }
            set {
                this.numField = value;
            }
        }
        
        /// <remarks/>
        public int Capacity {
            get {
                return this.capacityField;
            }
            set {
                this.capacityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetMoviesCompletedEventHandler(object sender, GetMoviesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMoviesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMoviesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Movie[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Movie[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetMoviesByTitleCompletedEventHandler(object sender, GetMoviesByTitleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMoviesByTitleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMoviesByTitleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Movie[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Movie[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetMoviesByPeriodCompletedEventHandler(object sender, GetMoviesByPeriodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMoviesByPeriodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMoviesByPeriodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Movie[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Movie[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void AddReservationCompletedEventHandler(object sender, AddReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Guid Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void RemoveReservationCompletedEventHandler(object sender, RemoveReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591